// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgwkCasfChqK647zKB2oKOzsuMmcfEGY',
    appId: '1:799290241291:web:7bcdddeed4fdb024adb20e',
    messagingSenderId: '799290241291',
    projectId: 'furnitureapp-b3bba',
    authDomain: 'furnitureapp-b3bba.firebaseapp.com',
    storageBucket: 'furnitureapp-b3bba.appspot.com',
    measurementId: 'G-J6LGHBP0X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrSyF4o2YAhxnXKLstEDBNtpKq1ZF9aU',
    appId: '1:799290241291:android:fd31b661811be11aadb20e',
    messagingSenderId: '799290241291',
    projectId: 'furnitureapp-b3bba',
    storageBucket: 'furnitureapp-b3bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-XHZdmbCp2nQkw2Iyv1s2mWB60XbRDfE',
    appId: '1:799290241291:ios:1c6d64fe1302eed5adb20e',
    messagingSenderId: '799290241291',
    projectId: 'furnitureapp-b3bba',
    storageBucket: 'furnitureapp-b3bba.appspot.com',
    androidClientId: '799290241291-tfeb06pmf3vc2p4s6tfm2jscnuci46et.apps.googleusercontent.com',
    iosClientId: '799290241291-7p3s0bj2ucrcvqsrm1uln22av4olhcb2.apps.googleusercontent.com',
    iosBundleId: 'furnitureapp-b3bba',
  );
}
